In [3]:
import pandas as pd
import numpy as np
from collections import Counter
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
cmap = ListedColormap(['#FF0000', '#00FF00', '#0000FF'])


In [10]:
df = pd.read_csv("/content/datasetmovies.csv")
attributes = df.columns.tolist()
print(attributes)
feature_names = attributes[0:2]
print(feature_names)
target_name = attributes[2]
print(target_name)




['No. of action scene', 'No.of comedy scene', 'Class/Label/categories']
['No. of action scene', 'No.of comedy scene', 'Class/Label/categories']
Class/Label/categories


In [14]:
df.head()

No. of action scene  No.of comedy scene Class/Label/categories
0                  100                  15                 Action
1                   20                  95                 comedy
2                   90                   5                 Action
3                   10                  85                 Comedy

In [15]:
df.describe()

No. of action scene  No.of comedy scene
count             4.000000            4.000000
mean             55.000000           50.000000
std              46.547467           46.547467
min              10.000000            5.000000
25%              17.500000           12.500000
50%              55.000000           50.000000
75%              92.500000           87.500000
max             100.000000           95.000000

In [16]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)


In [18]:
print(X_train)

[[ 10  85]
 [ 20  95]
 [100  15]]


In [19]:
print(y_train)

['Comedy' 'comedy' 'Action']


In [20]:
print(X_test)

[[90  5]]


In [21]:
print(y_test)

['Action']


In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) #avoid data leakage

In [25]:
print(X_train)

[[-0.82760589  0.56195149]
 [-0.57932412  0.84292723]
 [ 1.40693001 -1.40487872]]


In [26]:
print(X_test.dtype)

float64


In [31]:
def euclidean_distance(x1, x2):
    distance = np.sqrt(np.sum((x1-x2)**2))
    return distance

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def predict(self, X):
        predictions = [self._predict(x) for x in X]
        return predictions

    def _predict(self, x):
        # compute the distance
        distances = [euclidean_distance(x, x_train) for x_train in self.X_train]

        # get the closest k
        k_indices = np.argsort(distances)[:self.k]
        k_nearest_labels = [self.y_train[i] for i in k_indices]

        # majority vote
        most_common = Counter(k_nearest_labels).most_common()
        return most_common[0][0]

In [30]:
clf = KNN(k=5)
clf.fit(X_train, y_train)
predictions = clf.predict(X_test)

print(predictions)

acc = np.sum(predictions == y_test) / len(y_test)
print(acc)


['Action']
1.0
